// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/user/user_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "pr_reviewer_assignment_service/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, userID string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, userID)
}

// SetIsActive mocks base method.
func (m *MockUserRepository) SetIsActive(ctx context.Context, userID string, isActive bool) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserRepositoryMockRecorder) SetIsActive(ctx, userID, isActive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserRepository)(nil).SetIsActive), ctx, userID, isActive)
}

// MockPRGetter is a mock of PRGetter interface.
type MockPRGetter struct {
	ctrl     *gomock.Controller
	recorder *MockPRGetterMockRecorder
}

// MockPRGetterMockRecorder is the mock recorder for MockPRGetter.
type MockPRGetterMockRecorder struct {
	mock *MockPRGetter
}

// NewMockPRGetter creates a new mock instance.
func NewMockPRGetter(ctrl *gomock.Controller) *MockPRGetter {
	mock := &MockPRGetter{ctrl: ctrl}
	mock.recorder = &MockPRGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRGetter) EXPECT() *MockPRGetterMockRecorder {
	return m.recorder
}

// GetByReviewer mocks base method.
func (m *MockPRGetter) GetByReviewer(ctx context.Context, userID string) ([]*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReviewer", ctx, userID)
	ret0, _ := ret[0].([]*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReviewer indicates an expected call of GetByReviewer.
func (mr *MockPRGetterMockRecorder) GetByReviewer(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReviewer", reflect.TypeOf((*MockPRGetter)(nil).GetByReviewer), ctx, userID)
}
