// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/pr/pr_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entity "pr_reviewer_assignment_service/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPRRepository is a mock of PRRepository interface.
type MockPRRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPRRepositoryMockRecorder
}

// MockPRRepositoryMockRecorder is the mock recorder for MockPRRepository.
type MockPRRepositoryMockRecorder struct {
	mock *MockPRRepository
}

// NewMockPRRepository creates a new mock instance.
func NewMockPRRepository(ctrl *gomock.Controller) *MockPRRepository {
	mock := &MockPRRepository{ctrl: ctrl}
	mock.recorder = &MockPRRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRRepository) EXPECT() *MockPRRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPRRepository) Create(ctx context.Context, pr *entity.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPRRepositoryMockRecorder) Create(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPRRepository)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockPRRepository) GetByID(ctx context.Context, prID string) (*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, prID)
	ret0, _ := ret[0].(*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPRRepositoryMockRecorder) GetByID(ctx, prID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPRRepository)(nil).GetByID), ctx, prID)
}

// GetByReviewer mocks base method.
func (m *MockPRRepository) GetByReviewer(ctx context.Context, userID string) ([]*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReviewer", ctx, userID)
	ret0, _ := ret[0].([]*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReviewer indicates an expected call of GetByReviewer.
func (mr *MockPRRepositoryMockRecorder) GetByReviewer(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReviewer", reflect.TypeOf((*MockPRRepository)(nil).GetByReviewer), ctx, userID)
}

// Merge mocks base method.
func (m *MockPRRepository) Merge(ctx context.Context, prID string, pr *entity.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, prID, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockPRRepositoryMockRecorder) Merge(ctx, prID, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPRRepository)(nil).Merge), ctx, prID, pr)
}

// ReassignReviewer mocks base method.
func (m *MockPRRepository) ReassignReviewer(ctx context.Context, prID, oldUserID, newUserID string) (*entity.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldUserID, newUserID)
	ret0, _ := ret[0].(*entity.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockPRRepositoryMockRecorder) ReassignReviewer(ctx, prID, oldUserID, newUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockPRRepository)(nil).ReassignReviewer), ctx, prID, oldUserID, newUserID)
}
